name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
  build-release:
    strategy:
      matrix:
        version: [ '3.6', '3.7', '3.8', '3.9', '3.10']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v4.2.0
      with:
        python-version: ${{ matrix.version }}
    - name: Build egg
      run: python3 setup.py bdist_egg
    - name: Upload egg to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*.egg
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
